default_language_version:
  python: python3.14
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.1
    hooks:
      - id: uv-lock
      - id: uv-sync
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-format
      - id: ruff-check
  - repo: local
    hooks:
      - id: lint-imports
        name: import-linter
        entry: uv run lint-imports
        language: system
        pass_filenames: false
