fix = true

[lint]
select = ["ALL"]
ignore = ["COM812", "CPY001", "D203", "D213", "S603", "S607", "S608"]

[lint.per-file-ignores]
"tests/*" = ["ANN", "D103", "INP001", "S101"]
"packaging/*" = ["ANN", "D100", "D103", "INP001"]
